{{ if .Values.deployment.database.mongo.enabled }}
{{ if or (eq .Values.environment "staging") (eq .Values.environment "production") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-{{ .Release.Name }}
spec:
  refreshInterval: 24h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: gcp-secret-store # name of the SecretStore (or kind specified)
  target:
    name: mongodb-{{ .Release.Name }} # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          {{ if eq .Values.environment "staging" }}
          replicator.v1.mittwald.de/replicate-to-matching: lockerstock/feature-branch,lockerstock/{{ .Release.Name }}
          {{- end }}
  data:
    - secretKey: connectionString # name of the GCPSM secret key
      remoteRef:
        key: mongodb-{{ .Release.Name | replace "-" "_" }}-connection_string
{{- end }}
{{- end }}
