{{ if .Values.deployment.database.mongo.enabled }}
{{ if or (eq .Values.environment "staging") (eq .Values.environment "production") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  refreshInterval: 24h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: gcp-secret-store # name of the SecretStore (or kind specified)
  target:
    name: {{ .Release.Name }}-mongodb # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          {{- if eq .Values.environment "staging" }}
          replicator.v1.mittwald.de/replicate-to-matching: lockerstock/feature-branch,lockerstock/{{ .Release.Name }}
          {{- end }}
  data:
    - secretKey: db_password # name of the GCPSM secret key
      remoteRef:
        key: {{ include "microservice.shortName" . }}-mongodb-db_password
    - secretKey: server_domain # name of the GCPSM secret key
      remoteRef:
        key: {{ include "microservice.shortName" . }}-mongodb-server_domain
{{- end }}
{{- end }}
