apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "microservice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- if not (empty .Values.deployment.container.args) }}
          args: 
            {{- toYaml .Values.deployment.container.args | nindent 12 }}
          {{- end }}

          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: CONTAINER_IMAGE_NAME
              value: {{ .Values.image.repository }}
            - name: CONTAINER_IMAGE_TAG
              value: {{ .Values.image.tag | quote }}
            - name: CONTAINER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- if .Values.deployment.config.enabled }}      
            - name: LOG_LEVEL
              value: {{ .Values.deployment.config.LOG_LEVEL }}
            - name: LOG_FORMAT
              value: {{ .Values.deployment.config.LOG_FORMAT }}
            - name: GO_ENV
              value: {{ .Values.deployment.config.GO_ENV }}
            - name: GIN_MODE
              value: {{ .Values.deployment.config.GIN_MODE }}
            {{- end }}

            {{- if .Values.deployment.database.mongo.enabled }}
            - name: MONGO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{ .Release.Name }}-mongodb'
                  key: db_password
            - name: MONGO_SERVER_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: '{{ .Release.Name }}-mongodb'
                  key: server_domain
            {{- end }}

            {{- if .Values.deployment.opentelemetry.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: k8s-app-opentelemetry:4317
            {{- end }}

            {{- if .Values.deployment.cache.enabled }}
            - name: CACHE_ADDRESS
              value: {{ .Release.Name }}-cache:{{ .Values.deployment.cache.service.port }}
            {{- end }}

            {{- if .Values.deployment.auth0.enabled }}
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: '{{ .Release.Name }}-auth0'
                  key: AUTH0_DOMAIN
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: '{{ .Release.Name }}-auth0'
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: '{{ .Release.Name }}-auth0'
                  key: AUTH0_CLIENT_SECRET
            {{- end }}

            {{- if .Values.deployment.routing.enabled }}
            {{- if eq .Values.deployment.routing.strategy "loadbalancer" }}
            - name: LOAD_BALANCER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: loadbalancer-address
                  key: internal
            {{- end }}
            {{- end }}

            {{- if len .Values.deployment.env }}
            {{- toYaml .Values.deployment.env | nindent 12 }}
            {{- end }}

            {{- range $secretIndex, $secret := .Values.deployment.secrets }}
            {{- range $datumIndex, $datum := $secret.data }}
            {{- if not (empty $datum.env) }}
            - name: {{ $datum.env }}
              valueFrom:
                secretKeyRef:
                  name: '{{ $.Release.Name }}-{{ $secret.name }}'
                  key: {{ $datum.key }}
            {{- end }}
            {{- end }}
            {{- end }}

          {{- if not (empty .Values.deployment.probes.liveness) }}
          livenessProbe:
            {{- toYaml .Values.deployment.probes.liveness | nindent 12 }}
          {{- end }}
          {{- if not (empty .Values.deployment.probes.readiness) }}
          readinessProbe:
            {{- toYaml .Values.deployment.probes.readiness | nindent 12 }}
          {{- end }}
          {{- if not (empty .Values.resources) }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
