{{- if not (empty .Values.deployment.secrets) }}
{{- range $secretIndex, $secret := .Values.deployment.secrets }}
{{ if or (not $secret.replicate) (eq $.Values.environment "staging") (eq $.Values.environment "production") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $secret.name }}
  annotations:
    {{- if and $secret.replicate (eq $.Values.environment "staging") }}
    replicator.v1.mittwald.de/replicate-to-matching: lockerstock/feature-branch,lockerstock/{{ $.Release.Name }}
    {{- end }}

    {{- with $secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: {{ coalesce $secret.type "Opaque" }}
stringData:
  {{- range $datumIndex, $datum := $secret.data }}
  {{ $datum.key }}: {{ ternary (randAlphaNum (int ($datum.length | default 0))) ($datum.value) ($datum.random | default false) | nospace | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
