name: Publish Helm Chart

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-publish:
    name: Build and Publish Helm Chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - base-nginx

    env:
      registry: ghcr.io
      gcr_image: ghcr.io/${{ github.repository }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install helm
        uses: Azure/setup-helm@v3

      - name: Login to Helm Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.registry }} --username ${{ github.actor }} --password-stdin

      - name: Short Sha
        id: short
        uses: lockerstock/github-actions/get-short-sha@main

      - name: Get Chart Version
        id: chart
        run: echo "version=$(yq '.version' charts/${{ matrix.chart }}/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "version=${{ steps.chart.outputs.version }}-${{ steps.short.outputs.short_sha }}" >> $GITHUB_OUTPUT

          elif [ "${{ github.event_name }}" = "push" && "${{ github.ref_name }}" = "${{ github.event.repository.default_branch }}" ]; then
            echo "version=${{ steps.chart.outputs.version }}"

      - name: Update versions
        run: yq --inplace '.version = "${{ steps.version.outputs.variable }}"' Chart.yaml
        working-directory: ${{ inputs.chart_path }}

      - name: Package Helm Chart
        run: helm package ./charts/${{ matrix.chart }}

      - name: Publish Chart to Container Registry
        run: helm push ${{ matrix.chart }}-${{ steps.version.outputs.version }}.tgz oci://${{ env.gcr_image }}
