name: Publish Helm Chart

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-publish:
    name: Build and Publish Helm Chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - base-nginx

    env:
      registry: ghcr.io
      gcr_image: ${{ env.registry }}/${{ github.repository }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install helm
        uses: Azure/setup-helm@v1

      - name: Login to Helm Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.registry }} --username ${{ github.actor }} --password-stdin

      - name: Get Chart Version
        id: chart
        run: echo "version=$(yq '.version' charts/${{ matrix.chart }}/Chart.yaml)"" >> "$GITHUB_OUTPUT"

      - name: Package Helm Chart
        run: helm package ./charts/${{ matrix.chart }}

      - name: Publish Chart to Container Registry
        run: helm push ${{ matrix.chart }}-${{ steps.chart.outputs.version }}.tgz oci://${{ env.gcr_image }}
