name: Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/**/*"
      - ".github/workflows/publish.yaml"

jobs:
  build-and-publish:
    name: Build and Publish Helm Chart
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1 # this is to make sure there's no race condition whilst publishing to gh-pages
      matrix:
        chart:
          - microservice

    env:
      registry: ghcr.io
      gcr_image: ghcr.io/${{ github.repository }}

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install helm
        uses: Azure/setup-helm@v3

      - name: Get Chart Version
        id: chart
        run: echo "version=$(yq '.version' charts/${{ matrix.chart }}/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Package Helm Chart
        run: helm package ./charts/${{ matrix.chart }}

      ###### Tag and release Helm Chart ######

      - name: Auto Release from CHANGELOG
        id: changelog
        uses: lockerstock/github-actions/autoreleaser@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog_path: charts/${{ matrix.chart }}/CHANGELOG.md
          tag: ${{ steps.chart.outputs.version }}
          tag_prefix: "${{ matrix.chart }}@"
          artifacts: ${{ matrix.chart }}-${{ steps.chart.outputs.version }}.tgz
          replace_artifacts: true

      ###### Publish Helm Chart to GitHub Container Registry ######

      - name: Login to Helm Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.registry }} --username ${{ github.actor }} --password-stdin

      - name: Publish Chart to Container Registry
        run: helm push ${{ matrix.chart }}-${{ steps.chart.outputs.version }}.tgz oci://${{ env.gcr_image }}

      ###### Update gh-pages branch with newest package release ######

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: gh-pages
          path: gh-pages

      - name: Merge Helm Package into existing index
        run: |
          helm repo index . --merge gh-pages/index.yaml --url https://helm.lockerstock.io/charts/${{ matrix.chart }}

      - name: Move Helm Package and index into gh-pages
        run: |
          mv index.yaml gh-pages/
          mv ${{ matrix.chart }}-${{ steps.chart.outputs.version }}.tgz gh-pages/charts/${{ matrix.chart }}/

      - name: Push changes to gh-pages
        uses: EndBug/add-and-commit@v9
        with:
          cwd: gh-pages
          message: Release ${{ steps.prepared.outputs.tag }}
