name: Publish Helm Chart

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-publish:
    name: Build and Publish Helm Chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - base-nginx

    env:
      registry: ghcr.io
      gcr_image: ghcr.io/${{ github.repository }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install helm
        uses: Azure/setup-helm@v3

      - name: Login to Helm Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.registry }} --username ${{ github.actor }} --password-stdin

      - name: Short Sha
        id: short
        uses: lockerstock/github-actions/get-short-sha@main

      - name: Get Chart Version
        id: chart
        run: echo "version=$(yq '.version' charts/${{ matrix.chart }}/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Version
        id: version
        uses: lockerstock/github-actions/determine-environment@main
        with:
          token: ${{ inputs.token }}
          production_variable: ${{ steps.chart.outputs.version }}
          staging_variable: ${{ steps.chart.outputs.version }}
          development_variable: '${{ steps.chart.outputs.version }}-${{ steps.short.outputs.short_sha }}'

      - name: Update versions
        run: yq --inplace '.version = "${{ steps.version.outputs.variable }}"' Chart.yaml
        working-directory: ./charts/${{ matrix.chart }}

      - name: Package Helm Chart
        run: helm package ./charts/${{ matrix.chart }}

      - name: Publish Chart to Container Registry
        run: helm push ${{ matrix.chart }}-${{ steps.version.outputs.version }}.tgz oci://${{ env.gcr_image }}
