name: Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/**/*"

jobs:
  build-and-publish:
    name: Build and Publish Helm Chart
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1 # this is to make sure there's no race condition whilst publishing to gh-pages
      matrix:
        chart:
          - microservice

    env:
      registry: ghcr.io
      gcr_image: ghcr.io/${{ github.repository }}

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install helm
        uses: Azure/setup-helm@v3

      - name: Get Chart Version
        id: chart
        run: echo "version=$(yq '.version' charts/${{ matrix.chart }}/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Prepare Tag
        id: prepared
        run: echo "tag=${{ matrix.chart }}@${{ steps.chart.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        uses: lockerstock/github-actions/git-tag-exists@main
        id: tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.prepared.outputs.tag }}

      - name: Get Changelog Entry
        id: changelog_reader
        if: steps.tag.outputs.exists == 'false'
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          path: ./charts/${{ matrix.chart }}/CHANGELOG.md
          version: ${{ steps.chart.outputs.version }}

      - name: Package Helm Chart
        if: steps.tag.outputs.exists == 'false'
        run: helm package ./charts/${{ matrix.chart }}

      ###### Tag and release Helm Chart ######

      - name: Bump version and push tag
        id: tag_version
        if: steps.tag.outputs.exists == 'false'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.prepared.outputs.tag }}
          release_branches: ${{ github.event.repository.default_branch }}
          tag_prefix: ""

      - name: Create a GitHub release
        if: steps.tag.outputs.exists == 'false'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          artifacts: ${{ matrix.chart }}-${{ steps.chart.outputs.version }}.tgz
          replacesArtifacts: true
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          draft: false

      ###### Publish Helm Chart to GitHub Container Registry ######

      - name: Login to Helm Registry
        if: steps.tag.outputs.exists == 'false'
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.registry }} --username ${{ github.actor }} --password-stdin

      - name: Publish Chart to Container Registry
        if: steps.tag.outputs.exists == 'false'
        run: helm push ${{ matrix.chart }}-${{ steps.chart.outputs.version }}.tgz oci://${{ env.gcr_image }}

      ###### Update gh-pages branch with newest package release ######

      - name: Checkout gh-pages branch
        if: steps.tag.outputs.exists == 'false'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: gh-pages
          path: gh-pages

      - name: Merge Helm Package into existing index
        if: steps.tag.outputs.exists == 'false'
        run: |
          helm repo index . --merge gh-pages/index.yaml --url https://helm.lockerstock.io/charts/${{ matrix.chart }}

      - name: Move Helm Package and index into gh-pages
        if: steps.tag.outputs.exists == 'false'
        run: |
          mv index.yaml gh-pages/
          mv ${{ matrix.chart }}-${{ steps.chart.outputs.version }}.tgz gh-pages/charts/${{ matrix.chart }}/

      - name: Push changes to gh-pages
        if: steps.tag.outputs.exists == 'false'
        uses: EndBug/add-and-commit@v9
        with:
          cwd: gh-pages
          message: Release ${{ steps.prepared.outputs.tag }}
