name: Publish Helm Charts

on:
  push:
    branches:
      - main
      - feature/debug-publish-again

jobs:
  build-and-publish:
    name: Build and Publish Helm Chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - microservice
          - base-nginx

    env:
      registry: ghcr.io
      gcr_image: ghcr.io/${{ github.repository }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install helm
        uses: Azure/setup-helm@v3

      - name: Login to Helm Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.registry }} --username ${{ github.actor }} --password-stdin

      - name: Short Sha
        id: short
        uses: lockerstock/github-actions/get-short-sha@main

      - name: Get Chart Version
        id: chart
        run: echo "version=$(yq '.version' charts/${{ matrix.chart }}/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Chart Version Exists
        id: exists
        uses: lockerstock/github-actions/package-has-version@feature/central-helm-deploy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package_name: helm-charts/${{ matrix.chart }}
          package_version: ${{ steps.chart.outputs.version }}

      - name: Update versions
        run: yq --inplace '.version = "${{ steps.chart.outputs.version }}"' Chart.yaml
        working-directory: ./charts/${{ matrix.chart }}

      - name: Package Helm Chart
        run: helm package ./charts/${{ matrix.chart }}

      - name: Publish Chart to Container Registry
        if: steps.exists.outputs.version_exists == 'false'
        run: helm push ${{ matrix.chart }}-${{ steps.chart.outputs.version }}.tgz oci://${{ env.gcr_image }}
