name: Publish Helm Charts

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish Helm Chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - microservice
          - base-nginx

    env:
      registry: ghcr.io
      gcr_image: ghcr.io/${{ github.repository }}

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install helm
        uses: Azure/setup-helm@v3

      - name: Login to Helm Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.registry }} --username ${{ github.actor }} --password-stdin

      - name: Get Chart Version
        id: chart
        run: echo "version=$(yq '.version' charts/${{ matrix.chart }}/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Chart Version Exists
        id: exists
        uses: lockerstock/github-actions/package-has-version@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package_name: helm-charts/${{ matrix.chart }}
          package_version: ${{ steps.chart.outputs.version }}

      - name: Update versions
        run: yq --inplace '.version = "${{ steps.chart.outputs.version }}"' Chart.yaml
        working-directory: ./charts/${{ matrix.chart }}

      - name: Package Helm Chart
        run: helm package ./charts/${{ matrix.chart }}

      - name: Publish Chart to Container Registry
        if: steps.exists.outputs.version_exists == 'false'
        run: helm push ${{ matrix.chart }}-${{ steps.chart.outputs.version }}.tgz oci://${{ env.gcr_image }}

      - name: Get Changelog Entry
        id: changelog_reader
        if: steps.exists.outputs.version_exists == 'false'
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          path: ./charts/${{ matrix.chart }}/CHANGELOG.md

      - name: Bump version and push tag
        id: tag_version
        if: steps.exists.outputs.version_exists == 'false' && steps.changelog_reader.outputs.version == steps.chart.outputs.version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ matrix.chart }}@${{ steps.changelog_reader.outputs.version }}
          release_branches: ${{ github.event.repository.default_branch }}
          tag_prefix: ''

      - name: Create a GitHub release
        if: steps.exists.outputs.version_exists == 'false' && steps.changelog_reader.outputs.version == steps.chart.outputs.version
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          artifacts: ${{ matrix.chart }}-${{ steps.chart.outputs.version }}.tgz
          replacesArtifacts: true
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          makeLatest: ${{ matrix.chart != "base-nginx" }}
          draft: false
