name: Require CHANGELOG

on:
  pull_request:

jobs:
  require-changelog:
    name: Require CHANGELOG Entry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - microservice

    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            chart:
              - 'charts/${{ matrix.chart }}/**/*'

      - name: Checkout
        if: steps.changes.outputs.chart == 'true'
        uses: actions/checkout@v3

      ###### Check if latest tag in changelog has matching tag in repository ######

      - name: Get Changelog Entry
        if: steps.changes.outputs.chart == 'true'
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          path: ./charts/${{ matrix.chart }}/CHANGELOG.md

      - name: Check if tag already exists
        if: steps.changes.outputs.chart == 'true'
        uses: lockerstock/github-actions/git-tag-exists@main
        id: tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ matrix.chart }}@${{ steps.changelog_reader.outputs.version }}

      ###### Check if Unreleased section has new entry ######

      - name: Checkout default branch
        if: steps.changes.outputs.chart == 'true' && steps.tag.outputs.tag == 'true'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}
          path: default-branch

      - name: Get current Unreleased changelog entry
        if: steps.changes.outputs.chart == 'true' && steps.tag.outputs.tag == 'true'
        id: current-unreleased
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          path: ./charts/${{ matrix.chart }}/CHANGELOG.md
          version: Unreleased

      - name: Get default branch Unreleased changelog entry
        if: steps.changes.outputs.chart == 'true' && steps.tag.outputs.tag == 'true'
        id: default-unreleased
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          path: default-branch/charts/${{ matrix.chart }}/CHANGELOG.md
          version: Unreleased
