name: Require CHANGELOG

on:
  pull_request:

jobs:
  require-changelog:
    name: Require CHANGELOG Entry
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chart:
          - microservice

    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            chart:
              - 'charts/${{ matrix.chart }}/**/*'

      - name: Require Changelog Entry
        if: steps.changes.outputs.chart == 'true'
        id: changelog
        uses: lockerstock/github-actions/require-changelog-entry@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog_path: charts/${{ matrix.chart }}/CHANGELOG.md
          tag_prefix: "${{ matrix.chart }}@"
          error_on_missing: true

      ##### Check if new changelog version entry matches Chart.yaml #####

      - name: Checkout
        if: steps.changelog.outputs.has_new_version == 'true'
        uses: actions/checkout@v3

      - name: Get Chart Version
        if: steps.changelog.outputs.has_new_version == 'true'
        id: chart
        run: |
          VERSION=$(yq '.version' charts/${{ matrix.chart }}/Chart.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          if [ "$VERSION" = "${{ steps.changelog.outputs.changelog_latest_version }}" ]; then
            echo "matches=true" >> $GITHUB_OUTPUT
          else
            echo "matches=false" >> $GITHUB_OUTPUT
            echo "version-line=$(yq '.version | line' charts/${{ matrix.chart }}/Chart.yaml)" >> $GITHUB_OUTPUT
          fi

      - name: Print error if Chart.yaml version doesn't match changelog version
        if: steps.chart.outputs.matches == 'false'
        run: |
          echo "::error file=charts/${{ matrix.chart }}/Chart.yaml,line=${{ steps.chart.outputs.version-line }}::Chart version does not match to-be-released changelog entry. Please update the chart version to match before merging this pull request."
          exit 1
