name: Validate Helm Charts

on:
  pull_request:

jobs:
  validate-helm-charts:
    name: Validate Helm Charts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - microservice
          - base-nginx

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install helm
        uses: Azure/setup-helm@v3

      - name: Lint Helm Chart
        run: helm lint ./charts/${{ matrix.chart }}

      - name: Package Helm Chart
        run: helm package ./charts/${{ matrix.chart }}

      - name: Template Helm Chart
        run: helm template helm-charts ./charts/${{ matrix.chart }}
